service: defib-api

frameworkVersion: '3'

custom:
    stage: ${opt:stage, 'local'}
    region: ${opt:region, 'us-east-1'}
    resourcePrefix: ${self:service}-${self:custom.stage}

    esbuild:
        platform: node
        target: node20
        sourcemap: true
        plugins: esbuild.config.js

    env:
        PRISMA_QUERY_ENGINE_LIBRARY: ${self:custom.prismaEnginePath.${self:custom.stage}}

    prismaEnginePath:
        local: 'node_modules/.prisma/client/libquery_engine-darwin-arm64.dylib.node'
        qa: '/opt/prisma_engine.node'
        dev: '/opt/prisma_engine.node'
        staging: '/opt/prisma_engine.node'

    serverless-offline:
        httpPort: ${env:DEV_SERVER_PORT, 3000}
        noPrependStageInUrl: true
        reloadHandler: true

provider:
    name: aws
    stage: ${self:custom.stage}
    region: ${self:custom.region}
    runtime: nodejs20.x
    environment:
        DATABASE_URL: ${env:DATABASE_URL}
        PRISMA_QUERY_ENGINE_LIBRARY: ${self:custom.env.PRISMA_QUERY_ENGINE_LIBRARY}

    memorySize: 512
    timeout: 10
    logRetentionInDays: 7

    logs:
        httpApi: true
    httpApi: # Add this block
        payload: '1.0' # Key fix: Use v1.0 for Express compatibility

layers:
    prismaEngine:
        path: layers/prisma-engine
        name: ${self:custom.resourcePrefix}-prisma-engine
        compatibleRuntimes: [nodejs20.x]

plugins:
    - serverless-dotenv-plugin
    - serverless-esbuild
    - serverless-offline

functions:
    app:
        handler: src/handlers/app.handler
        layers:
            - { Ref: PrismaEngineLambdaLayer }
        events:
            - httpApi:
                  path: /app/{proxy+}
                  method: '*'

    iot:
        handler: src/handlers/iot.handler
        layers:
            - { Ref: PrismaEngineLambdaLayer }
        events:
            - httpApi:
                  path: /iot/data
                  method: '*'

    ws-connect:
        handler: src/handlers/websockets/connect.handler
        events:
            - websocket:
                  events: $connect

    ws-disconnect:
        handler: src/handlers/websockets/disconnect.handler
        events:
            - websocket:
                  events: $connect

    ws-connect:
        handler: src/handlers/websockets/default.handler
        events:
            - websocket:
                  events: $default
